### ISSUE TITLE
Explain gains over 'aws s3 sync ...'

### ISSUE THREAD

**Issue by pjz** [scripting/publicfolder#1]
Is this essentially an `aws s3 sync` command run once a minute?

**Comment by scripting** [comment]
It's realtime. Built on Chokidar. The files upload as soon as you save them in the folder. It's more like Radio's upstreaming feature (2002) or Dropbox's public folder feature (which worked until Sept 1). People always want to know why something isn't "just X" -- believe me, if this existed I would not have wasted my time doing it. It's also going to be part of an Electron app for people who don't like command lines.

**Comment by pjz** [comment]
>The first question is (of course): "Why isn't it just like everything else ever done?" 

Product differentiation is a thing.

**Comment by scripting** [comment]
Indeed! I'm a huge believer in understanding where your product fits in. No criticism intended, just two different perspectives.
