### ISSUE TITLE
Change first sentence of README.md...

### ISSUE THREAD

**Issue by richb-hanover** [scripting/publicfolder#2]
If I understand correctly, you should change the first sentence of the README...

From: 

> publicFolder is a Node app that runs on your desktop and keeps a single folder in sync with a location on Amazon S3.

To:

> publicFolder is a Node app that runs on your desktop and keeps a location on Amazon S3 synchronized with a single folder (the "master") on your local machine.

**Comment by scripting** [comment]
Thanks for the report. I think you're right. I changed the description to -- 

> A Node app that runs on your desktop and keeps an S3 location in sync with a folder on a local disk.

**Comment by richb-hanover** [comment]
Ermmm... I don't mean to be fussy, but the update hasn't made it to the README file...

(My company's unofficial motto is, "We promise not to fix it if we don't know it's broke..." :-) Thanks.

**Comment by scripting** [comment]
I changed the tagline on the project, forgot to change the first sentence of the readme. The change should be there now. Sorry for the delay.

**Comment by richb-hanover** [comment]
Thanks!
