### ISSUE TITLE
Uploading loop

### ISSUE THREAD

**Issue by elliotclowes** [scripting/publicfolder#5]
Hi Dave. Thanks for this great tool!

I'm installing it for the first time and having a small issue. Everything seems to be working and uploading to my S3 bucket okay, but for some reason there seems to be some sort of uploading loop?

Any help would be greatly appreciated it!

![Screenshot 2021-09-12 at 21 55 07](https://user-images.githubusercontent.com/2827932/133002616-f0f93a1c-d36b-4692-ac25-f91ce8e9c317.png)

**Comment by scripting** [comment]
@elliotclowes -- It works fine here. 

You might have a look in the JavaScript console to see if there are any error messages.

Stare at your configuration file, and see if anything could be wrong there. 

Basically you have to figure it out. I have my own systems to keep running. The software works, I depend on it.

**Comment by elliotclowes** [comment]
Solved it :)

"s3Folder" was set to an S3 bucket. By changing "s3Folder" to a folder _within_ the bucket seems to have fixed things.
